_parent_: options/base.yaml

arch:                                                       # architectural options
    layers: [null,256,256,256,256,3]                        # hidden layers for MLP
    skip: []                                                # skip connections
    posenc:                                                 # positional encoding
        L_2D: 8                                             # number of bases (3D point)

barf_c2f:                                                   # coarse-to-fine scheduling on positional encoding

data:                                                       # data options
    image_fname: data/ttacff-152_1024.jpg                               # path to image file
    image_size: [1024,1024]                                   # original image size
    patch_crop: [256,256]                                   # crop size of image patches to align

warp:                                                       # image warping options
    type: homography                                        # type of warp function (homography, rigid, rotation, translation)
    dof: 8                                                  # degrees of freedom of the warp function
    noise_h: 0.1                                            # scale of pre-generated warp perturbation (homography)
    noise_t: 0.2                                            # scale of pre-generated warp perturbation (translation)
    fix_first: true                                         # fix the first patch for uniqueness of solution

loss_weight:                                                # loss weights (in log scale)
    render: 0                                               # RGB rendering loss

optim:                                                      # optimization options
    lr: 1.e-3                                               # learning rate (main)
    lr_warp: 1.e-3                                          # learning rate of warp parameters

batch_size: 5                                               # batch size (set to number of patches to consider)
max_iter: 1000                                              # train to maximum number of iterations

visdom:                                                     # Visdom options (turned off)

freq:                                                       # periodic actions during training
    scalar: 20                                              # log losses and scalar states (every N iterations)
    vis: 10                                                # visualize results (every N iterations)

